In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

raw_data = pd.read_csv("bennet.csv")
x = raw_data[['team', 'targeted_productivity', 'standard_minute_value', 'work_in_progress', 
              'over_time', 'incentive', 'idle_time', 'idle_men', 'no_of_style_change', 'no_of_workers']]   #.iloc[:,:-1]
y = raw_data.iloc[:,-1]

In [13]:
from sklearn.model_selection import train_test_split
x_training_data, x_test_data, y_training_data, y_test_data = train_test_split(x, y, test_size = 0.3)

from sklearn.svm import SVC
model = SVC()
model.fit(x_training_data, y_training_data)
predictions1 = model.predict(x_test_data)

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
print(classification_report(y_test_data, predictions1))

#plot_decision_regions(x_training_data, y_training_data,clf=model, legend=2)

# Update plot object with X/Y axis labels and Figure Title
#plt.xlabel(X.columns[0], size=14)
#plt.ylabel(X.columns[1], size=14)
#plt.title('SVM Decision Region Boundary', size=16)
#plt.show()

#svcc = SVC(kernel='linear') #linear kernal
#svcc.fit(x_training_data, y_training_data)
#rbf_svc = SVC(kernel='rbf', gamma=0.7).fit(x_training_data, y_training_data)
#poly_svc = SVC(kernel='poly', degree=3).fit(x_training_data, y_training_data)
#lin_svc = svm.LinearSVC(C=C).fit(x_training_data, y_training_data)

#predictions2 = svcc.predict(x_test_data)
#predictions3 = rbf_svc.predict(x_test_data)
#predictions4 = poly_svc.predict(x_test_data)

#print(classification_report(y_test_data, predictions2))
#print(classification_report(y_test_data, predictions3))
#print(classification_report(y_test_data, predictions4))

              precision    recall  f1-score   support

 0.23 - 0.38       0.00      0.00      0.00        19
 0.38 - 0.54       0.00      0.00      0.00        25
 0.54 - 0.69       0.00      0.00      0.00        61
 0.69 - 0.84       0.50      0.72      0.59       152
    0.84 - 1       0.40      0.55      0.47       103

    accuracy                           0.46       360
   macro avg       0.18      0.25      0.21       360
weighted avg       0.33      0.46      0.38       360



C:\Users\Ben\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [11]:
print(confusion_matrix(y_test_data, predictions1))


[[  0   0   0  16   5]
 [  0   0   0  19   8]
 [  0   0   0  34  33]
 [  0   0   0 115  35]
 [  0   0   0  39  56]]
